#!/bin/sh
export DEBEMAIL=htcondor-admin@cs.wisc.edu
DEBIAN_FRONTEND=noninteractive mk-build-deps --install --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' debian/control
mkdir -p package
(cd package; for i in ../*.tar.gz; do tar xfpz $i; done)
rm -rf package/*/debian
mv debian package/*/
cd package/*
mv ../../*.tar.gz ..
rm -f ../../*build-deps*
dch --release --distribution stable ignored
. /etc/os-release
if [ "$VERSION_CODENAME" = 'bullseye' ]; then
    true
elif [ "$VERSION_CODENAME" = 'bookworm' ]; then
    dch --distribution stable --nmu 'place holder entry'
elif [ "$VERSION_CODENAME" = 'focal' ]; then
    true
elif [ "$VERSION_CODENAME" = 'jammy' ]; then
    dch --distribution stable --nmu 'place holder entry'
else
    echo ERROR: Unknown codename "${VERSION_CODENAME}"
    exit 1
fi
dpkg-buildpackage -uc -us
ret=$?
cd ..
cp -p * ..
cd ..
rm -rf package
exit $ret
