#!/bin/sh
export DEBEMAIL=htcondor-admin@cs.wisc.edu
DEBIAN_FRONTEND=noninteractive mk-build-deps --install --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' debian/control
mkdir -p package
(cd package; for i in ../*.tar.gz; do tar xfpz $i; done)
rm -rf package/*/debian
mv debian package/*/
cd package/*
mv ../../*.tar.gz ..
rm -f ../../*build-deps*
dch --release --distribution stable ignored
sed -r -i '1s/-[0-9]+/&+SYS99/' debian/changelog
. /etc/os-release
if [ "$VERSION_CODENAME" = 'bullseye' ]; then
    SYS99='deb11'
elif [ "$VERSION_CODENAME" = 'bookworm' ]; then
    SYS99='deb12'
elif [ "$VERSION_CODENAME" = 'trixie' ]; then
    SYS99='deb13'
elif [ "$VERSION_CODENAME" = 'focal' ]; then
    SYS99='ubu20'
elif [ "$VERSION_CODENAME" = 'jammy' ]; then
    SYS99='ubu22'
elif [ "$VERSION_CODENAME" = 'noble' ]; then
    SYS99='ubu24'
elif [ "$VERSION_CODENAME" = 'resolute' ]; then
    SYS99='ubu26'
elif [ "$VERSION_CODENAME" = 'chimaera' ]; then
    SYS99='dev04'
else
    echo ERROR: Unknown codename "${VERSION_CODENAME}"
    exit 1
fi

if grep -q SYS99 debian/changelog; then
    sed -i s/SYS99/$SYS99/ debian/changelog
else
    echo ERROR: SYS99 not present in changelog
    exit 1
fi
dpkg-buildpackage -uc -us
ret=$?
cd ..
cp -p * ..
cd ..
rm -rf package
exit $ret
